version : '3.8'


services: 

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE="restaurant-rating"
    ports: 
      - 27017:27017

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=username
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    ports: 
      - 8081:8081